### ISSUE TITLE
RecycleView. 怎么用 ？

### ISSUE THREAD

**Issue by i91h1r** [zzzlw/autovideoplayer#2]
如题.   @Override public void onScrolled(RecyclerView recyclerView, int dx, int dy) {} 他的和listview 的不一样额

**Comment by QinAndroid** [comment]
@hyr0318 我也遇到了 请问你解决了吗？

**Comment by zzzlw** [comment]
@hyr0318 @QinAndroid 
          LinearLayoutManager manager = (LinearLayoutManager) recyclerView.getLayoutManager();
                    int lastCompletelyVisibleItemPosition = manager.findLastCompletelyVisibleItemPosition();
同理还有firstVisible, 然后就 一样了
